#!/bin/sh
#linked from ~/.vnc
xrdb $HOME/.Xresources
#xsetroot -solid black

#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &
# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1
#/etc/X11/Xsession

fbsetbg /usr/share/games/tmw/data/graphics/images/login_wallpaper.png



